---
- name: Install and Configure PostgreSQL on Linux  hosts
  hosts: all
  become: yes
  tasks:

    - name: Verify that the latest Red Hat Subscription Manager is present
      yum:
        name: subscription-manager
        state: latest

    - name: Register system into RHSM
      redhat_subscription:
        state: present
        username: "{{ rhsm_username }}"
        password: "{{ rhsm_password }}"
        force_register: yes
    
    - name: Including PostgreSQL role
      include_role:
        name: postgresql
      vars:
        postgresql_databases:
          - name: "{{ postgresql_db }}"
        postgresql_users:
          - name: "{{ postgresql_username }}"
            password: "{{ postgresql_password }}"
